### ISSUE TITLE
Speech Recognition Problem arise

### ISSUE THREAD

**Issue by YY-8885** [jayeshbhandarkar/GlobalSpeak#1]
C:\Users\Administrator\Desktop\GlobalSpeak-main>app.py
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:8000 (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 486-686-638
127.0.0.1 - - [31/Jul/2024 16:10:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2024 16:10:16] "GET /static/css/style.index.css HTTP/1.1" 304 -
127.0.0.1 - - [31/Jul/2024 16:10:16] "GET /static/images/final_logo.png HTTP/1.1" 304 -
127.0.0.1 - - [31/Jul/2024 16:10:16] "GET /static/images/bgimage.png HTTP/1.1" 304 -
127.0.0.1 - - [31/Jul/2024 16:10:20] "GET /static/utilities/video_translate.html HTTP/1.1" 304 -
127.0.0.1 - - [31/Jul/2024 16:10:20] "GET /static/css/style.forms.css HTTP/1.1" 304 -
127.0.0.1 - - [31/Jul/2024 16:10:20] "GET /static/js/connector.js HTTP/1.1" 304 -
127.0.0.1 - - [31/Jul/2024 16:10:20] "GET /static/js/editor.js HTTP/1.1" 304 -
127.0.0.1 - - [31/Jul/2024 16:10:20] "GET /static/js/languageListAdder.js HTTP/1.1" 304 -
inside video_transcript
request.form:  ImmutableMultiDict([('target_language', 'chinese (simplified)')])
<FileStorage: '蒜香鱼片.mp4' ('video/mp4')> zh-cn
file saved
MoviePy - Writing audio in static/audio_from_video/audio.wav
chunk:  13%|███████▉                                                      | 102/800 [00:00<00:00, 944.55it/s, nochunk:  42%|█████████████████████████▍                                   | 333/800 [00:00<00:0chunk:  70%|██████████████████████████████████████████▊                  | 56MoviePy - Done.
audio extracted
127.0.0.1 - - [31/Jul/2024 16:10:38] "POST /video_translate HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Administrator\Desktop\GlobalSpeak-main\app.py", line 125, in translate_video
    video_translator(r'static/audio_from_video/audio.wav', target, videoclip)
  File "C:\Users\Administrator\Desktop\GlobalSpeak-main\app.py", line 133, in video_translator
    transcript = r.recognize_google(audio, key=None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\speech_recognition\__init__.py", line 858, in recognize_google
    if not isinstance(actual_result, dict) or len(actual_result.get("alternative", [])) == 0: raise UnknownValueError()
speech_recognition.UnknownValueError

**Comment by jayeshbhandarkar** [comment]
During the translation process (line 133 of your app.py), an UnknownValueError is raised by the speech_recognition library. This error indicates that the Google Speech Recognition service couldn't understand the audio content. Ensure that audio file has good quality and is clear.
